// Test data for scraper demonstration
export const MOCK_TENDERS = [
  {
    source: 'ilan_gov' as const,
    source_id: 'test_001',
    source_url: 'https://www.ilan.gov.tr/ilan/123456',
    title: 'Askeri Birliklerin Catering Hizmeti İhalesi',
    organization: 'Milli Savunma Bakanlığı',
    organization_city: 'Ankara',
    budget: 5000000,
    deadline_date: new Date('2025-12-15'),
    announcement_date: new Date('2025-10-20'),
    tender_type: 'Açık İhale',
    procurement_type: 'Hizmet Alımı',
    category: 'Yemek Hizmetleri',
  },
  {
    source: 'ilan_gov' as const,
    source_id: 'test_002',
    source_url: 'https://www.ilan.gov.tr/ilan/123457',
    title: 'Üniversite Öğrenci Yemekhanesi Catering Alımı',
    organization: 'İstanbul Teknik Üniversitesi',
    organization_city: 'İstanbul',
    budget: 12000000,
    deadline_date: new Date('2025-11-30'),
    announcement_date: new Date('2025-10-15'),
    tender_type: 'Açık İhale',
    procurement_type: 'Hizmet Alımı',
    category: 'Yemek Hizmetleri',
  },
  {
    source: 'ilan_gov' as const,
    source_id: 'test_003',
    source_url: 'https://www.ilan.gov.tr/ilan/123458',
    title: 'Hastane Yemek Servisi Hizmeti',
    organization: 'Ankara Şehir Hastanesi',
    organization_city: 'Ankara',
    budget: 8500000,
    deadline_date: new Date('2025-12-01'),
    announcement_date: new Date('2025-10-18'),
    tender_type: 'Açık İhale',
    procurement_type: 'Hizmet Alımı',
    category: 'Yemek Hizmetleri',
  },
];
